jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "node"
      script: npm test
    - stage: test
      language: python
      python: 3.8
      script: python src/data-wrangling/csv_to_json_test.py
    - stage: deploy
      if: branch = gh-pages
      language: python
      python: 3.8
      script: python
        src/data-wrangling/csv_to_json.py
        src/data-wrangling/wid-data.csv > src/data.json

#deploy:
#  edge: true
#  provider: pages:git
#  on:
#    branch: gh-pages
